algoritmo "atividade 4"

var
   nota1:real;
   nota2:real;
   nota3:real;
   nota4:real;
   media:real;
inicio

      nota1<-2;
      nota2<-3;
      nota3<-4;
      nota4<-6;
      media<-(nota1,nota2,nota3,nota4)/4
      se nota>7 entao
      escreval("você esta aprovado, parabens, teve media de:", media)
      senao
      escreval("você não ficou na media, estude mais, teve media de:", media)
      fimse
fimalgoritmo